name: Fingerprint
inputs:
  echoserver-filename:
    required: true
  unique-platform-id:
    required: true
  run:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: echoserver

    - shell: bash
      id: main
      run: |
        chmod +x ${{ inputs.echoserver-filename }}
        ${{ inputs.echoserver-filename }} -verbose &
        ${{ inputs.run }}

        FILENAME=$(echo "fingerprint_${{ inputs.unique-platform-id }}.json" | sed 's/:/_/g')
        echo FILENAME=$FILENAME > $GITHUB_OUTPUT

        cat fingerprint.json | jq '{
          "unique-platform-id": "${{ inputs.unique-platform-id }}"
        } + .' > $FILENAME

        ls -la

        kill %1
        wait

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.main.outputs.FILENAME }}
        path: ${{ steps.main.outputs.FILENAME }}
