name: Fingerprint
inputs:
  echoserver-filename:
    required: true
  unique-platform-id:
    required: true
  run:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: echoserver

    - shell: bash
      run: |
        chmod +x ${{ inputs.echoserver-filename }}
        ${{ inputs.echoserver-filename }} -verbose &
        ${{ inputs.run }}
        cat fingerprint.json | jq '{
          "unique-platform-id": "${{ inputs.unique-platform-id }}"
        } + .' > fingerprint_${{ inputs.unique-platform-id }}.json
        kill %1
        wait

    - uses: actions/upload-artifact@v4
      with:
        name: fingerprint_${{ inputs.unique-platform-id }}.json
        path: fingerprint_${{ inputs.unique-platform-id }}.json
