name: Fingerprint
inputs:
  echoserver-filename:
    required: true
  unique-filename-suffix:
    required: true
  run:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: echoserver

    - shell: bash
      run: |
        chmod +x ${{ inputs.echoserver-filename }}
        ${{ inputs.echoserver-filename }} -verbose &
        ${{ inputs.run }}
        mv fingerprint.json fingerprint_${{ inputs.unique-filename-suffix }}.json
        kill %1
        wait

    - uses: actions/upload-artifact@v4
      with:
        name: fingerprint_${{ inputs.unique-filename-suffix }}.json
        path: fingerprint_${{ inputs.unique-filename-suffix }}.json
