name: Generate fingerprints

on:
  push:
    branches: ["master"]

jobs:
  generate:
    name: Generate
    runs-on: ${{ matrix.os }}

    strategy:
      max-parallel: 2
      matrix:
        # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners
        os:
          - ubuntu-22.04
          - windows-2022
          - macos-13
        env:
          - &go
            setup: go
            version: ~1.19.0
            run: go run ./go/main.go

          - <<: *go
            version: ~1.20.0

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-${{ matrix.env.setup }}@v5
        with:
          go-version: ${{ matrix.env.version }}

      - run: ${{ matrix.env.run }}

      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: fingerprint
      #     path: fingerprint.json
