name: Generate fingerprints

on:
  push:
    branches: ["master"]

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners
        os:
          - ubuntu-22.04
          - windows-2022
          - macos-13
        setup:
          - language: go
            version: ~1.21.0
        # exclude:
        #   - os: macos-latest
        #     version: 12
        #     environment: production
        #   - os: windows-latest
        #     version: 16

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.setup.version }}

      - run: go get
      - run: make build
        env:
          CGO_ENABLED: 0

      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: fingerprint
      #     path: fingerprint.json