name: Generate fingerprints

on:
  push:
    branches: ["master"]

jobs:
  build-echoserver:
    name: Build Fingerproxy echoserver
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: "0"
      GOARCH: amd64
      BUILD_DIR: ./example/echo-server
    steps:
      - uses: actions/checkout@v4
        with:
          repository: wi1dcard/fingerproxy

      - uses: actions/setup-go@v5
        with:
          go-version: ~1.21.0

      # filenames are according to os matrix below
      - run: ./testdata/gencert.sh
      - run: GOOS=linux go build -o echoserver_ubuntu-22.04 $BUILD_DIR
      - run: GOOS=windows go build -o echoserver_windows-2022 $BUILD_DIR
      - run: GOOS=darwin go build -o echoserver_macos-13 $BUILD_DIR

      - uses: actions/upload-artifact@v4
        with:
          name: echoserver
          path: |
            echoserver_*
            tls.crt
            tls.key

  aggregate-json:
    name: Aggregate
    runs-on: ubuntu-latest
    needs:
      - go
      - go-060
      - curl
      - curl-mingw
      - curl-container
      - python
      - python-container
      # ...
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: fingerprint_*.json
          merge-multiple: true

      - run: |
          jq -s . fingerprint_*.json > aggregated.json
          {
            echo '```json'
            cat aggregated.json
            echo '```'
          } > $GITHUB_STEP_SUMMARY

      - uses: actions/upload-artifact@v4
        with:
          name: aggregated.json
          path: aggregated.json

  go:
    name: Go
    runs-on: ${{ matrix.os }}
    needs: build-echoserver
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          # same:
          # - windows-2022
          # - macos-13
        version:
          - ~1.21.0
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        id: setup
        with:
          go-version: ${{ matrix.version }}
          cache: false

      - uses: ./.github/fingerprint-action
        with:
          echoserver-filename: ./echoserver_${{ matrix.os }}
          unique-platform-id: go-${{ steps.setup.outputs.go-version }}-${{ matrix.os }}
          run: |
            cd go
            go run ./main.go
            mv fingerprint.json ..

  go-060:
    name: Go 060
    runs-on: ${{ matrix.os }}
    needs: build-echoserver
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          # same:
          # - windows-2022
          # - macos-13
        version:
          - ~1.17.0
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        id: setup
        with:
          go-version: ${{ matrix.version }}
          cache: false

      - uses: ./.github/fingerprint-action
        with:
          echoserver-filename: ./echoserver_${{ matrix.os }}
          unique-platform-id: go060-${{ steps.setup.outputs.go-version }}-${{ matrix.os }}
          run: |
            cd go-0.6.0
            go run ./main.go
            mv fingerprint.json ..

  curl:
    name: Curl
    runs-on: ${{ matrix.os }}
    needs: build-echoserver
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-13]
    steps:
      - uses: actions/checkout@v4

      - if: startsWith(matrix.os, 'windows')
        shell: bash
        run: |
          curl -o curl.zip https://curl.se/windows/dl-8.6.0_1/curl-8.6.0_1-win64-mingw.zip
          unzip curl.zip
          mv ./curl-*/bin/* /mingw64/bin

      - uses: ./.github/fingerprint-action
        with:
          echoserver-filename: ./echoserver_${{ matrix.os }}
          unique-platform-id: curl-${{ matrix.os }}
          run: ./curl/curl.sh --http2

  curl-mingw:
    name: Curl mingw
    runs-on: ${{ matrix.os }}
    needs: build-echoserver
    strategy:
      matrix:
        os: [windows-2022]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/fingerprint-action
        with:
          echoserver-filename: ./echoserver_${{ matrix.os }}
          unique-platform-id: curl-mingw-${{ matrix.os }}
          run: ./curl/curl.sh

  curl-container:
    name: Curl container
    runs-on: ubuntu-22.04
    needs: build-echoserver
    strategy:
      matrix:
        image:
          - ubuntu:18.04
          - ubuntu:20.04
          - ubuntu:22.04
          - debian:12
          - debian:11
          - debian:10
          - centos:6
          - centos:7
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/fingerprint-action
        with:
          echoserver-filename: ./echoserver_ubuntu-22.04
          unique-platform-id: curl-container-${{ matrix.image }}
          run: |
            [[ "${{ matrix.image }}" = centos:* ]] && HTTP2="" || HTTP2="--http2"

            docker run --add-host=host.docker.internal:host-gateway \
              --rm -v $PWD:/src ${{ matrix.image }} \
              bash -c "cd /src && ./curl/curl-container.sh $HTTP2"

  python:
    name: Python
    runs-on: ${{ matrix.os }}
    needs: build-echoserver
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, windows-2022, macos-13]
        version:
          - "3.12"
          # as same as:
          # - "3.11"
          # - "3.10"
          - "3.9"
          # as same as:
          # - "3.8"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        id: setup
        with:
          python-version: ${{ matrix.version }}
      - uses: ./.github/fingerprint-action
        with:
          echoserver-filename: ./echoserver_${{ matrix.os }}
          unique-platform-id: python-${{ steps.setup.outputs.python-version }}-${{ matrix.os }}
          run: |
            python ./python/httpclient.py
            pip install requests && python ./python/with-requests.py
            pip install httpx 'httpx[http2]' && python ./python/with-httpx.py
            # as same as http.client:
            # pip install aiohttp && python ./python/with-aiohttp.py

  python-container:
    name: Python container
    runs-on: ubuntu-22.04
    needs: build-echoserver
    strategy:
      matrix:
        image:
          - python:3.12-bookworm
          - python:3.8-bookworm
          - python:3.12-bullseye
          - python:3.8-bullseye
          # alpine results are quite as same as debian
          # - python:3.12-alpine
          # - python:3.8-alpine
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/fingerprint-action
        with:
          echoserver-filename: ./echoserver_ubuntu-22.04
          unique-platform-id: python-container-${{ matrix.image }}
          run: |
            docker run --add-host=localhost:host-gateway \
              --rm -v $PWD:/src ${{ matrix.image }} \
              sh -c "cd /src && python ./python/httpclient.py"

            docker run --add-host=localhost:host-gateway \
              --rm -v $PWD:/src ${{ matrix.image }} \
              sh -c "cd /src && pip install requests && python ./python/with-requests.py"

            docker run --add-host=localhost:host-gateway \
              --rm -v $PWD:/src ${{ matrix.image }} \
              sh -c "cd /src && pip install httpx 'httpx[http2]' && python ./python/with-httpx.py"

            # as same as http.client:
            # docker run --add-host=localhost:host-gateway \
            #   --rm -v $PWD:/src ${{ matrix.image }} \
            #   sh -c "cd /src && pip install aiohttp && python ./python/with-aiohttp.py"

  node:
    name: Node
    runs-on: ${{ matrix.os }}
    needs: build-echoserver
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-13]
        version:
          - 21.x
          # as same as:
          # - 20.x
          # - 19.x
          # - 18.x
          # - 17.x
          - 16.x
          # as same as:
          # - 15.x
          - 14.x
          - 13.x
          - 12.x
          - 11.x
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        id: setup
        with:
          node-version: ${{ matrix.version }}
      - uses: ./.github/fingerprint-action
        with:
          echoserver-filename: ./echoserver_${{ matrix.os }}
          unique-platform-id: node-${{ steps.setup.outputs.node-version }}-${{ matrix.os }}
          run: |
            cd node
            npm i
            node http2.js
            node https.js
            node superagent.js
            mv fingerprint.json ..
